### ISSUE TITLE
All Jobs throw ArgumentCountError after php & ubuntu upgrade 

### ISSUE THREAD

**Issue by StagasaurusRex** [mjphaynes/php-resque#89]
We recently updated from ubuntu 14.04 and php 5.6 to ubuntu 16.04 and php 7.1, and all of our jobs are now throwing an ArgumentCountError. 
It would seem that php-resque is no longer sending our arguments to the job, despite being present in the logs.

Any ideas?

```
[2019-03-18 11:08:12] resque.NOTICE: Found a job default:xxxxx\Jobs\GenerateFeedNotificationJob#e35e00df169918e6db616f([60481]) [] []
[2019-03-18 11:08:12] resque.DEBUG: Forked process to run job on pid:2536 [] []
[2019-03-18 11:08:12] resque.INFO: Running job default: xxxxx\Jobs\GenerateFeedNotificationJob#e35e00df169918e6db616f([60481]) [] []
[2019-03-18 11:08:12] resque.ERROR: Job default: xxxxx\Jobs\GenerateFeedNotificationJob#e35e00df169918e6db616f([60481]) failed: "Uncaught ArgumentCountError: Too few arguments to function xxxxx\Jobs\GenerateFeedNotificationJob::__construct(), 0 passed and exactly 1 expected in /var/www/wol-devbox.local/dev/current/src/xxxxx/Jobs/GenerateFeedNotificationJob.php:28 Stack trace: #0 [internal function]: xxxxx\Jobs\GenerateFeedNotificationJob->__construct() #1 /var/www/wol-devbox.local/dev/current/vendor/mjphaynes/php-resque/src/Resque/Job.php(381): ReflectionClass->newInstance() #2 /var/www/wol-devbox.local/dev/current/vendor/mjphaynes/php-resque/src/Resque/Job.php(317): Resque\Job->getInstance() #3 /var/www/wol-devbox.local/dev/current/vendor/mjphaynes/php-resque/src/Resque/Worker.php(362): Resque\Job->perform() #4 /var/www/wol-devbox.local/dev/current/vendor/mjphaynes/php-resque/src/Resque/Worker.php(340): Resque\Worker->perform(Object(Resque\Job)) #5 /var/www/wol-devbox.local/dev/current/vendor/mjphaynes/php-resque/src/Resque/Commands/Worker/Start.php(72): Resque\Worker->work() #6 /var/www/wol-devbox.local/dev/current/ in /var/www/wol-devbox.local/dev/current/src/xxxxx/Jobs/GenerateFeedNotificationJob.php on line 28" in 426.1ms [] []
```

**Comment by xelan** [comment]
Hi @StagasaurusRex!

Thank you for posting this issue and your interest in the php-resque project.

We've been using php-resque with PHP 7.1 for years now, without any specific issues. Do you have a minimal example to reproduce your issue? Maybe you could post the signature of your `GenerateFeedNotificationJob` class and how you enqueue your jobs.

Best regards
Andreas

**Comment by StagasaurusRex** [comment]
Hi xelan. Thanks for the quick reply, as I was typing out my response to you I think I found the issue. I'll enumerate it here for posterity.

Here is how I was enqueuing jobs,

```
class Jobs
{
    /**
     * Load Resque config
     */
    public static function loadConfig()
    {
        if (getenv('APP_ENV') === "prod") {
            try {
                \Resque::loadConfig(getenv("APP_HOME_DIR") . "/config/php-resque/config.yml");
            } catch (\Exception $e) {
                Log::error("Error loading php resque config.", $e);
                return;
            }
        }
    }

    /**
     * Run job ASAP.
     * @param JobInterface $job
     */
    public static function enqueueJob(JobInterface $job)
    {
        Log::error("Enqueueing job", null, [$job->getJobType(), $job->getArgs()]);
        self::loadConfig();

        Log::error("G");
        \Resque::queue()->push(
            $job->getJobType()->getValue(),
            $job->getArgs()
        );
    }
}
```

And here is an example JobInterface,

```
class GenerateFeedNotificationJob implements JobInterface
{
    /**
     * @var int
     */
    protected $id;

    /**
     * GenerateFeedNotificationJob constructor.
     * @param $id
     */
    public function __construct($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getJobType()
    {
        return JobType::GENERATE_FEED_NOTIFICATIONS();
    }

    /**
     * @return array
     */
    public function getArgs()
    {
        return [$this->id];
    }

    /**
     * @param $args
     * @throws \Exception
     */
    public function perform($args)
    {
        $post = new Post($args['id']);
        $notifications = NotificationManager::generateNotifications($post);
        foreach ($notifications as $notification) {
            $emailNotificationCycle = $notification->profile()->preferences()->emailNotificationCycle();
            if ($emailNotificationCycle->equals(EmailNotificationCycle::ASAP())) {
                EmailNotifications::sendInstantEngagementEmail($notification);
            }
        }
    }
}
```

Basically, I was using the same class to enqueue and perform the job, and I failed to realize that (of course) php-resque is instantiating the object without passing in args to the constructor. Presumably, php started complaining about argument count errors sometime in between 5.6 and 7.1. 

Thanks again @xelan.

**Comment by xelan** [comment]
I'm glad that I could help to resolve your issue. The best practice is to use slim job classes which delegate the actual tasks to services.
